apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: metadata
  name: metadata
spec:
  type: NodePort
  ports:
  - name: "metadata"
    port: 8080
    targetPort: 8080
    nodePort: 30020
  selector:
    io.kompose.service: metadata
status:
  loadBalancer: {}
