apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
