apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: books
  name: books
spec:
  type: NodePort
  ports:
  - name: "books"
    port: 8080
    targetPort: 8080
    nodePort: 30020
  selector:
    io.kompose.service: books
status:
  loadBalancer: {}
