apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
    spec:
      containers:
      - image: eu.gcr.io/gleaming-store-226116/bookshop-gateway
        name: gateway
        ports:
        - containerPort: 8080
status: {}
