apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  type: NodePort
  ports:
  - name: "gateway"
    port: 8080
    targetPort: 8080
    nodePort: 30090
  selector:
    io.kompose.service: gateway
status:
  loadBalancer: {}
