apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  type: NodePort
  ports:
  - name: "mongo"
    port: 27017
    targetPort: 27017
    nodePort: 30070
  selector:
    io.kompose.service: mongo
status:
  loadBalancer: {}
